### ISSUE TITLE
Function 'buffMaintain( effect )' undefined.

### ISSUE THREAD

**Issue by industrialpunk** [Loathing-Associates-Scripting-Society/crimbo#21]
Function 'buffMaintain( effect )' undefined. This script may require a more recent version of KoLmafia and/or its supporting scripts. (crimbo21.ash, line 259, char 3 to char 15)

When trying to run script I get this error. I am guessing an additional dependency is missing.

**Comment by taltamir** [comment]
> Function 'buffMaintain( effect )' undefined. This script may require a more recent version of KoLmafia and/or its supporting scripts. (crimbo21.ash, line 259, char 3 to char 15)
> 
> When trying to run script I get this error. I am guessing an additional dependency is missing.

@industrialpunk

The dependency is autoscend. which has a problem with updating due to how mafia is using svn to access git (and github bad support for svn accessing git)

You should reinstall autoscend to force it to update to latest version. I should add a version check here to verify autoscend is up to date rather than merely installed

**Comment by taltamir** [comment]
From the discord:

> Some people (myself included) had issues with mafia failing to update scripts. Where even uninstall and reinstall does not solve the issue.
> 
> Some issues are caused by mafia using svn to access git. which causes some conflicts with github due to a problem with github's support for svn access.
Mafia does not expose svn errors and they just silently fail without making it clear to the user that a failure occurs. 
> 
> especially url change issues if you moved from beta to master branch.
They can even cause the svn local repo to not be properly purged on uninstall
> 
> If you have typical updating problems you can solve it by uninstalling and reinstalling. (see pinned messages for instructions on how to do so).
> 
> If uninstalling and reinstalling does not work properly then you might have a case where it is failing to delete the svn dir on uninstall. In such a case you want to go into your mafia folder and delete the autoscend folder inside the /svn/ directory. If mafia is sufficently broken you might have to delete the entire /svn/ directory
> 
> This will completely purge all script install states. The scripts will still exist in the scripts folder. But they will not be considered installed nor will they get updates.
> 
> At this point you then want to go ahead and reinstall the scripts you use. it will recreate the svn database and reinstall autoscend and all dependent scripts as needed. it will repeatedly ask you if you are sure you want to overwrite files (once per each dependent script being installed), say yes every time.
> 
> If the window asking you if you are sure extends beyond your screen just hit the enter key on your keyboard. it defaults to having the YES button selected in case of hitting enter 

and

> If you install autoscend and it gives an error that files or functions cannot be found.
> 
> this sometimes happens when we move, rename, or add new files. When such a thing occurs mafia gives a popup asking for new permissions and warns you to only say yes if you trust the source, it sounds scary so people say no. It is also easy to accidentally click no. Even if you say yes this can still occur if you got a test version via discord instead of via svn
> 
> There is no point waiting for us to fix it because it is your local installation that got broken. You need to reinstall autoscend to fix it.
> 
> to uninstall type in CLI:
> `svn delete autoscend`
> after uninstalling you can install it again. for Beta use CLI:
> `svn checkout https://github.com/Loathing-Associates-Scripting-Society/autoscend/branches/master/RELEASE/`
> 
> Do not worry, all your settings will be retained. you will not lose anything.

**Comment by industrialpunk** [comment]
> 

Thank you. Deleting and reinstalling fixed the issue. I really appreciate the help :) Happy Holidays!

**Comment by taltamir** [comment]
> Thank you. Deleting and reinstalling fixed the issue. I really appreciate the help :) Happy Holidays!

Merry crimbo
